### ISSUE TITLE
Support Cabal 2.4.*

### ISSUE THREAD

**Issue by kozross** [ennocramer/floskell#31] opened 2019-05-04 21:01 UTC
Currently, `cabal new-install` fails as follows:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-2.4.1.0, Cabal-2.4.0.1/installed-2.4..., Cabal-2.4.0.1,
Cabal-2.4.0.0 (constraint from user target requires ==2.2.0.1)
[__0] trying: Cabal-2.2.0.1
[__1] next goal: containers (user goal)
[__1] rejecting: containers-0.6.0.1/installed-0.6..., containers-0.6.0.1
(conflict: Cabal => containers>=0.4.2.1 && <0.6)
[__1] rejecting: containers-0.5.11.0, containers-0.5.10.2,
containers-0.5.10.1, containers-0.5.9.2, containers-0.5.8.2,
containers-0.5.7.1, containers-0.5.7.0, containers-0.5.6.3,
containers-0.5.6.2, containers-0.5.6.1, containers-0.5.6.0,
containers-0.5.5.1, containers-0.5.5.0, containers-0.5.4.0,
containers-0.5.3.1, containers-0.5.3.0, containers-0.5.2.1,
containers-0.5.2.0, containers-0.5.1.0, containers-0.5.0.0,
containers-0.4.2.1, containers-0.4.2.0, containers-0.4.1.0,
containers-0.4.0.0, containers-0.3.0.0, containers-0.2.0.1,
containers-0.2.0.0, containers-0.1.0.1, containers-0.1.0.0,
containers-0.5.9.1, containers-0.5.8.1 (constraint from user target requires
==0.6.0.1)
[__1] fail (backjumping, conflict set: Cabal, containers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Cabal, containers
```

**Comment by ennocramer** [comment] 2019-05-08 10:46
I'm not sure what's going on here.

Running `cabal new-install floskell` (cabal-install-2.4.1.0, installing floskell-0.10.0) works fine for me. Floskell also should not reject `containers-0.6.0.1` since version 0.9.0-r2 (March, 7th).  Maybe a `cabal update` will help?

**Comment by kozross** [comment] 2019-05-08 21:38
Still getting this issue. Here's a fuller console log:

```sh
[koz@Sebastian ~]$ cabal new-update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal new-update 'hackage.haskell.org,2019-05-04T20:14:38Z'
[koz@Sebastian ~]$ cabal new-install -w $(which ghc) -O2 floskell
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-2.4.1.0, Cabal-2.4.0.1/installed-2.4..., Cabal-2.4.0.1,
Cabal-2.4.0.0 (constraint from user target requires ==2.2.0.1)
[__0] trying: Cabal-2.2.0.1
[__1] next goal: containers (user goal)
[__1] rejecting: containers-0.6.0.1/installed-0.6..., containers-0.6.0.1
(conflict: Cabal => containers>=0.4.2.1 && <0.6)
[__1] rejecting: containers-0.5.11.0, containers-0.5.10.2,
containers-0.5.10.1, containers-0.5.9.2, containers-0.5.8.2,
containers-0.5.7.1, containers-0.5.7.0, containers-0.5.6.3,
containers-0.5.6.2, containers-0.5.6.1, containers-0.5.6.0,
containers-0.5.5.1, containers-0.5.5.0, containers-0.5.4.0,
containers-0.5.3.1, containers-0.5.3.0, containers-0.5.2.1,
containers-0.5.2.0, containers-0.5.1.0, containers-0.5.0.0,
containers-0.4.2.1, containers-0.4.2.0, containers-0.4.1.0,
containers-0.4.0.0, containers-0.3.0.0, containers-0.2.0.1,
containers-0.2.0.0, containers-0.1.0.1, containers-0.1.0.0,
containers-0.5.9.1, containers-0.5.8.1 (constraint from user target requires
==0.6.0.1)
[__1] fail (backjumping, conflict set: Cabal, containers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Cabal, containers

[koz@Sebastian ~]$ which ghc
/bin/ghc
[koz@Sebastian ~]$ $(which ghc) --version
The Glorious Glasgow Haskell Compilation System, version 8.6.4
[koz@Sebastian ~]$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

**Comment by ennocramer** [comment] 2019-05-09 14:07
I can not reproduce this error, even with `ghc-8.6.4`.

I've found mention of a bug in Cabal, about picking up constraints from global configuration files.  Can you check your `~/.ghc/` directory for any such file that mentions `Cabal` or `containers`? Or maybe something in your `~/.cabal/config`?

```shell
$ which ghc
/Users/enno.cramer/.stack/programs/x86_64-osx/ghc-8.6.4/bin/ghc

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.4

$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library

$ cabal new-update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal new-update 'hackage.haskell.org,2019-05-09T12:20:21Z'

$ cabal new-install -w $(which ghc) -O2 floskell
Resolving dependencies...
Build profile: -w ghc-8.6.4 -O2
In order, the following will be built (use -v for more details):
.
.
.
Starting     floskell-0.10.0 (exe:floskell)
Building     floskell-0.10.0 (exe:floskell)
Installing   floskell-0.10.0 (exe:floskell)
Completed    floskell-0.10.0 (exe:floskell)
Symlinking 'floskell'
cabal: Path '/Users/enno.cramer/.cabal/bin/floskell' already exists. Use
--overwrite-policy=always to overwrite.```

**Comment by ennocramer** [comment] 2020-09-21 19:22
I'm closing this issue. Feel free to comment if this is still an issue.

**Closed as completed by ennocramer** 2020-09-21 19:22 UTC
